/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.CuentaDef;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio Aranda
 */
public class CuentaDefault extends javax.swing.JFrame {

    /**
     * Creates new form CuentaDefault
     */
    public CuentaDefault() {
        initComponents();
        cargarLista("SELECT * FROM `cuenta`;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECCIONE LA CUENTA POR DEFECTO PARA SU PLANTILLA");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (guardar()) {
            JOptionPane.showMessageDialog(null, "PLANTILLA GUARDADA");
            this.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR");
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentaDefault().setVisible(true);
            }
        });
    }

    public void cargarLista(String query) {

        int nivel;
        int otro_nivel;
        try {
            //Nueva conexion
            Conexion conecta = new Conexion();
            ResultSet rs, rs1;
            rs = conecta.Consulta(query, conecta.getConexion());

            //removemos todo del combo box
            jComboBox1.removeAllItems();

            //mientras halla otro dato en rs, añadimos a la combo box un resultado
            while (rs.next()) {
                nivel = Integer.parseInt(rs.getString(3));
                if (nivel > 2) {

                    jComboBox1.addItem(rs.getString(4) + rs.getString(2));
                }
            }
            //cerramos la conexion cerrando el resultado obtenido

            rs.close();
            conecta.close();

        } catch (SQLException ex) {
            Logger.getLogger(AgregarPartida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean guardar() {
        CuentaDef cu = new CuentaDef();
        String cuenta = "";
        String cod = "";
        char c;
        String combo = jComboBox1.getSelectedItem().toString();
        for (int i = 0; i < jComboBox1.getSelectedItem().toString().length(); i++) {
            c = combo.charAt(i);
            if (Character.isLetter(c)) {
                cuenta += String.valueOf(c);
            } else if (c == ' ') {
                cuenta += String.valueOf(c);
            } else {
                cod += String.valueOf(c);
            }

        }

        Conexion con = new Conexion();
        con.Ejecutar("INSERT INTO `plantilla`(`IdPlantilla`, `NombrePlantilla`, `CuentaDefault`, `TipoIVA`) VALUES (NULL,'" + cuenta + "','" + cod + "','Ninguno')");

        ResultSet rs = con.Consulta("SELECT * FROM `plantilla` order by `IdPlantilla` DESC limit 1 ", con.getConexion());

        String ultimo = "";
        try {
            if (rs.next()) {
                ultimo = rs.getString("IdPlantilla");
            }
            con.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(AgPlantilla.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        String datos[][] = cu.getTabla();
        String idCuenta = "";
        for (int i = 0; i < cu.getnFila(); i++) {
            rs = con.Consulta("SELECT `id_cuenta` FROM `cuenta` WHERE `codigo`= '" + datos[i][0] + "'", con.getConexion());
            try {
                if (rs.next()) {
                    idCuenta = rs.getString("id_cuenta");
                }
                con.close();
                rs.close();
                con.Ejecutar("INSERT INTO `cuentaenplantilla`(`IdCuentaEnPlantilla`, `cuenta_id`, `Debe`, `Haber`, `Plantilla_id`) VALUES (NULL,'" + idCuenta + "','" + datos[i][2] + "','" + datos[i][3] + "','" + ultimo + "')");

            } catch (SQLException ex) {
                Logger.getLogger(AgPlantilla.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
